\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{pye-resumen}

\LoadClass[a4paper]{article}

\RequirePackage[hidelinks]{hyperref}
%\RequirePackage[spanish]{babel}
\RequirePackage[utf8]{inputenc}
%\RequirePackage[T1]{fontenc}
\RequirePackage{geometry}
\RequirePackage{graphicx}
\RequirePackage{url}
\RequirePackage{fancyhdr}
\RequirePackage{scrextend}
\RequirePackage{float}
%\RequirePackage{upquote}
\RequirePackage{listings}
\RequirePackage{xcolor}
%\RequirePackage{tikz}
%\RequirePackage{helvet}
\RequirePackage{etoolbox}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
%\RequirePackage[type={CC},modifier={by-nc-sa},version={4.0}]{doclicense}

% Configurar márgenes
\geometry{top=2.5cm, bottom=2.7cm, left=2.5cm, right=2.5cm}

% Configurar sans-serif como fuente predeterminada
\renewcommand{\familydefault}{\sfdefault} 
